version: 2
updates:

  # Enable version updates for nuget
  - package-ecosystem: "nuget"
    directory: "/ImperatorToCK3/"
    # Check the nuget registry for updates every day (weekdays) schedule:
    schedule:
      interval: "daily"
      
  - package-ecosystem: "nuget"
    directory: "/ImperatorToCK3.UnitTests/"
    # Check the nuget registry for updates every day (weekdays) schedule:
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
