version: dev.{build}
image: Visual Studio 2019 Preview
configuration: Release
build_script:
- cmd: >-
    git submodule update --init --recursive

    msbuild -m ImperatorToCK3.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

test_script:
- ps: >-

    ImperatorToCK3Tests\Release\ImperatorToCK3Tests.exe --gtest_output=xml:tests.xml

    $wc = New-Object 'System.Net.WebClient'

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\tests.xml))
artifacts:
- path: Release
  name: ImperatorToCK3-$(APPVEYOR_REPO_TAG_NAME)
deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: Stable release
  auth_token:
    secure: LBJzs4y9j0N5y0ajp7gmVk3Pvnec1UU5pTCdIMbQYUddEXQnWTJ79FXsd9SCs7YQ
  repository: ParadoxGameConverters/ImperatorToCK3
  artifact: ImperatorToCK3-$(APPVEYOR_REPO_TAG_NAME)
  prerelease: false
  force_update: true
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only