l_simp_chinese:
 IMPDISPLAYNAME: "英白拉多：罗马至十字军之王III"
 IMPGAME: "英白拉多：罗马"
 IMPFOLDER: "英白拉多：罗马 安装路径"
 IMPFOLDERTIP: "在你电脑上英白拉多：罗马的安装路径"
 IMPMOD: "英白拉多：罗马 Mod路径"
 IMPMODTIP: "在你电脑上英白拉多：罗马存放mod的位置"
 CK3GAME: "十字军之王III"
 CK3FOLDER: "十字军之王III 安装路径"
 CK3FOLDERTIP: "在你电脑上十字军之王III的安装路径"
 CK3MOD: "十字军之王III Mod路径"
 CK3MODTIP: "在你电脑上十字军之王III存放mod的位置"
 IMPFILE: "转换器可执行文件路径"
 IMPFILETIP: "ImperatorToCK3Converter.exe所在的路径"
 IMPSAVE: "英白拉多：罗马 存档路径"
 IMPSAVETIP: "你的英白拉多：罗马存档所在的路径"