name: "Publish commit id"

on:
  release:
    types: [published]

jobs:
  publish_id:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Publish commit id
      uses: ParadoxGameConverters/publish_commit_id@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        destination_file: 'ImperatorToCK3.txt'
        user_email: 'idhrendur@hotmail.com'
        user_name: 'idhrendur'
        destination_branch: 'main'
        commit_message: "Publish ImperatorToCK3's commit id"
