name: "Test code signing for Mac"
on:
  pull_request:

jobs:
  test_code_signing:
    runs-on: macos-latest
    environment: "Build Environment"
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
    - name: "Setup Dotnet for use with actions"
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: Fronter.NET/global.json
    - name: "Build frontend"
      uses: ./Fronter.NET/.github/actions/build_frontend
      with:
        fronter_dir: 'Fronter.NET'
        release_dir: 'Publish'
      env:
        BACKBLAZE_KEY_ID: ${{ secrets.BACKBLAZE_KEY_ID }}
        BACKBLAZE_APPLICATION_KEY: ${{ secrets.BACKBLAZE_APPLICATION_KEY }}
        BACKBLAZE_BUCKET_ID: ${{ secrets.BACKBLAZE_BUCKET_ID }}
    - name: "Check frontend code signature"
      run: |
        codesign -dv --verbose=4 ./Publish/ConverterFrontend
    - name: "Setup Dotnet for use with actions"
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json
    - name: "Build backend"
      working-directory: ImperatorToCK3
      run: |
        dotnet publish -p:PublishProfile=osx-arm64 -c:Release --output:"../Publish/ImperatorToCK3"
    - name: "Sign backend"
      run: |
        codesign --force -s - ./Publish/ImperatorToCK3/ImperatorToCK3Converter
    - name: "Check backend code signature"
      run: |
        codesign -dv --verbose=4 ./Publish/ImperatorToCK3/ImperatorToCK3Converter
