name: Test Linux build

on:
  push:
    branches:
      - test-wf

jobs:
  test_wf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: "Init submodules"
      run: |
       git submodule update --init --recursive
    - name: Setup Dotnet for use with actions
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.*'
    - name: "Build frontend"
      uses: ./Fronter/.github/actions/build_frontend
    - name: "Build backend"
      run: |
        cd ImperatorToCK3
        dotnet publish -p:PublishProfile=linux-x64 -c:Release
        cd ..
        rm -r "Release/ImperatorToCK3"
        cp -R Publish/ Release/
    - name: "Save commit ID"
      run: |
       git rev-parse HEAD > Release/commit_id.txt
    - name: Archive Release folder
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        directory: Release/
        filename: 'ImperatorToCK3-linux-x64.zip'
    - name: Print directory tree
      run: |
       sudo apt-get install tree
       tree
