name: "Validate DDS files"

on:
  pull_request:
  merge_group:

concurrency:
  group: ci-validate-dds-files-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  validate-dds-files:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - uses: mfinelli/setup-imagemagick@v6
      with:
        install-libfuse2: true
    - name: "Install Wand library"
      run: |
        python3 -m venv venv
        source venv/bin/activate
        python3 -m pip install Wand
    - name: "Validate faith icons"
      run: |
        source venv/bin/activate
        python3 ./tools/validate_dds_files.py