name: "Validate DDS files"

on:
  pull_request:
  merge_group:

concurrency:
  group: ci-validate-dds-files-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  validate-dds-files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: mfinelli/setup-imagemagick@v5
    - name: "Validate faith icons"
      shell: python
      run: |
        # make sure every file in ImperatorToCK3/Data_Files/blankMod/output/gfx/icons/faith/ is valid: .dds, 100x100 pixels, format: 32bit-A8R8G8B8, no mipmaps
        # Based on CK3 mod coop FAQ on DDS files:
        # https://discord.com/channels/735413460439007241/948759032326410240/1214691391737823263

        # find all .dds files in the faith icons directory
        import os
        faith_icons_dir = "ImperatorToCK3/Data_Files/blankMod/output/gfx/interface/icons/faith/"
        faith_icons = [faith_icons_dir + f for f in os.listdir(faith_icons_dir) if f.endswith(".dds")]

        # check each file
        for faith_icon in faith_icons:
          # check if the file is a valid .dds file
          if os.system(f"magick identify -format %m {faith_icon}") != 0:
            print(f"Invalid .dds file: {faith_icon}")
            exit(1)

          # check if the file is 100x100 pixels
          if os.system(f"magick identify -format %w {faith_icon}") != 100 or os.system(f"magick identify -format %h {faith_icon}") != 100:
            print(f"Incorrect size: {faith_icon}")
            exit(1)

          # check if the file is 32bit-A8R8G8B8
          if os.system(f"magick identify -format %z {faith_icon}") != "32":
            print(f"Incorrect format: {faith_icon}")
            exit(1)

          # check if the file has no mipmaps
          if os.system(f"magick identify -format %m {faith_icon}") != "1":
            print(f"Has mipmaps: {faith_icon}")
            exit(1)
