name: "Validate DDS files"

on:
  pull_request:
  merge_group:

concurrency:
  group: ci-validate-dds-files-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  validate-dds-files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: mfinelli/setup-imagemagick@v5
      with:
        cache: true
        install-libfuse2: true
    - name: "Validate faith icons"
      run: |
        python3 ./tools/validate_dds_files.py